#!/bin/sh
# -------------------------------------------------------------------------------------------
# @author: Araf Karsh Hamid
# -------------------------------------------------------------------------------------------
echo "Starting `getServiceName` Microservice"
export JDK_JAVA_OPTIONS="--add-opens=jdk.management/com.sun.management.internal=ALL-UNNAMED"
runMode=$1
# Check if the runMode is null or not one of "dev", "prod", or "staging"
if [[ -z $runMode || ($runMode != "dev" && $runMode != "prod" && $runMode != "staging") ]]
then
  runMode="dev"
fi
echo "App running with profile = $runMode"

# Run Maven Command
# mvn spring-boot:run -Dspring-boot.run.profiles=$runMode

# Run Java command
echo "java -jar target/ms-vanilla-service-*-spring-boot.jar --spring.profiles.active=$runMode"
#java -Djava.security.policy=./vanilla.policy -jar target/ms-vanilla-service-*-spring-boot.jar --spring.profiles.active=$runMode
#java -Dlogging.level.org.springframework.aop.framework=DEBUG -jar target/ms-vanilla-service-*-spring-boot.jar --spring.profiles.active=$runMode
java -jar target/ms-vanilla-service-*-spring-boot.jar --spring.profiles.active=$runMode  -Djava.security.manager=java.lang.SecurityManager -Djava.security.policy=./vanilla.policy

