#!/bin/bash
# -------------------------------------------------------------------------------------------
# @author: Araf Karsh Hamid, (c) Copyright 2024
# -------------------------------------------------------------------------------------------
# Description: This script performs HTTP GET requests to a specified API endpoint.
#              It accepts a command line parameter for the number of iterations:
#              - If the parameter is -1, it runs in an infinite loop.
#              - If the parameter is missing, it defaults to 1000 iterations.
# -------------------------------------------------------------------------------------------
# while true; do   curl -X 'GET' 'http://localhost:9334/ms-vanilla/api/v1/product/all/' -H 'accept: application/json';   echo "Query done"; done
# -------------------------------------------------------------------------------------------

# Check if a command-line argument is provided
if [ -z "$1" ]; then
  # No argument provided, default to 1000 iterations
  iterations=1000
elif [ "$1" -eq -1 ]; then
  # Infinite loop if the argument is -1
  iterations=-1
else
  # Use the provided number of iterations
  iterations=$1
fi
echo "------------------------------------------------------------------------------------------------------------"
echo "Performance Testing..... "
echo "curl -X 'GET' 'http://localhost:9334/ms-vanilla/api/v1/product/all/' -H 'accept: application/json'"
echo "------------------------------------------------------------------------------------------------------------"

# Loop
count=1
while true; do
  echo "{$count}"
  # Perform the curl request
  curl -X 'GET' 'http://localhost:9334/ms-vanilla/api/v1/product/all/' -H 'accept: application/json'
  echo

  # Check if we are in a finite loop and increment the counter
  if [ $iterations -ne -1 ]; then
    if [ $count -ge $iterations ]; then
      break
    fi
    count=$((count + 1))
  fi
done
echo
echo "Processing done...."
