#!/bin/sh
# ============================================================================
# Export Database 
# @author: Araf Karsh Hamid, (c) Copyright 2022-24
# ============================================================================
pg_dump -U postgres -h localhost -p 5433 -d ms_vanilla_334 -n ms_schema > ms-sb334_new.sql
