#!/bin/sh
# -------------------------------------------------------------------------------------------
# @author: Araf Karsh Hamid
# -------------------------------------------------------------------------------------------
echo keytool -printcert -file fusionAir.cer
keytool -printcert -file fusionAir.cer
