#!/bin/sh
# -------------------------------------------------------------------------------------------
# @author: Araf Karsh Hamid
# -------------------------------------------------------------------------------------------
echo keytool -exportcert -alias fusionAir -file fusionAir.der -keystore fusionAir.pkcs12 -storetype pkcs12
keytool -exportcert -alias fusionAir -file fusionAir.der -keystore fusionAir.pkcs12 -storetype pkcs12
